project_id = "urwcoxzikudihxazthth"

[functions.generate-quiz]
verify_jwt = false

[functions.admin-stats]
verify_jwt = false

[functions.send-daily-email]
verify_jwt = false

[functions.unsubscribe]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false
